version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.0
jobs:
  android-debug-build:
    executor:
      name: android/android-machine
      resource-class: xlarge
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Assemble debug build
          command: |
            ./gradlew assemble
      - store_artifacts:
          path: app/build/outputs/apk/debug
  test: 
    working_directory: ~/repo
    docker:
      - image: 'cimg/node:16.17-browsers'
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm run test:nowatch
  web-build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.17.0
    steps:
      - checkout
      - run:
          name: install-ionic
          command: "sudo npm install -g @ionic/cli"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: build-prod
          command: ionic build --prod
          
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - web-build
      - android-debug-build