version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.17.0
    environment:
      CHROME_BIN: /usr/bin/google-chrome
    orbs:
      browser-tools: circleci/browser-tools@1.4.0
    steps:
      - checkout
      - run:
          name: install-browser-tools
          command: "browser-tools/install-browser-tools"
      - run:
          name: install-ionic
          command: "sudo npm install -g @ionic/cli"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: build-prod
          command: ionic build --prod
      - run:
          name: test
          command: npm run test